name: Keep Backend Awake

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: true

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: date

      - name: Curl your backend with retry and error logging
        run: |
          for i in {1..3}; do
            echo "Attempt $i to ping backend"
            if curl -sS --fail-with-body https://avail-it-1.onrender.com/api/hospitals/getAllHospitals; then
              echo "✅ Backend responded successfully."
              break
            else
              echo "❌ Attempt $i failed. Retrying in 5 seconds..."
              sleep 5
            fi
          done
