name: Keep Backend Awake

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl your backend
        run: |
          curl -sSf https://avail-it-1.onrender.com/api/hospitals/getAllHospitals || true 