name: Keep Backend Awake

on:
  schedule:
    # Runs every 6 minutes
    - cron: '*/6 * * * *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Print current time
        run: date
      - name: Curl your backend
        run: |
          curl -sSf https://avail-it-1.onrender.com/api/hospitals/getAllHospitals || true 